version: '3.4'

services:
  db:
    container_name: mongo_rentgame
    image: mongo:4.4.6
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "27017:27017"
    networks:
      - rentgame-network
  rentgame:
    container_name: rentgame
    image: rentgameimage
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    command: mvn spring-boot:run
    links:
      - db
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - rentgame-network
networks:
  rentgame-network:
    driver: bridge
