POST http://10.0.0.147:8080/games/fanout/1
Content-Type: application/json

{
    "name": "Uncharted",
    "category":"Adventure",
    "dateOfRelease":"2002-12-23"
}
#####
POST http://10.0.0.147:8080/games/fanout/2
Content-Type: application/json

{
    "name": "Uncharted",
    "category":"Adventure",
    "dateOfRelease":"2002-12-23"
}
####
POST http://10.0.0.147:8080/games/fanout/3
Content-Type: application/json

{
    "name": "Uncharted",
    "category":"Adventure",
    "dateOfRelease":"2002-12-23"
}