#configurações spring
spring:
  data:
    mongodb:
      uri: mongodb://10.0.0.147/rentgames
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
###configurações rabbitmq
  rabbitmq:
    host: 10.0.0.147
    port: 5672
    username: admin
    password: 123456
      
##configurações tipo direct      
nome:
  exchange:
    rabbitmq: rent_games_exchange_fanout
  routingKey:
    fanout1: routing_key1
    fanout2: routing_key2
    fanout3: routing_key3
  queue:
    fila1: fila1
    fila2: fila2
    fila3: fila3
server:
  port: 8081