#configurações spring
spring:
  data:
    mongodb:
      uri: mongodb://10.0.0.147/rentgames
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
###configurações rabbitmq
  rabbitmq:
    host: 10.0.0.147
    port: 5672
    username: admin
    password: 123456
      
##configurações tipo topic      
nome:
  exchange:
    rabbitmq: rent_games_exchange_topic
  routingKey:
    topic1: routing.capital.mg
    topic2: routing.capital.sp
    topic3: routing.interior.sp
    topic4: routing.capital.*
    topic5: routing.interior.*
  queue:
    fila1: routing-capital-mg
    fila2: routing-capital-sp
    fila3: routing-interior-sp
    fila4: routing-todosdacapital
    fila5: routing-todosdointerior