#configurações spring
spring:
  data:
    mongodb:
      uri: mongodb://10.0.0.147/rentgames
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
###configurações rabbitmq
  rabbitmq:
    host: 10.0.0.147
    port: 5672
    username: admin
    password: 123456
      
##configurações tipo direct      
nome:
  exchange:
    rabbitmq: rent_games_exchange_headers
  queue:
    fila1: passando_todos_os_parametros_do_header
    fila2: passando_algum_dos_parametros_do_header
    fila3: onde_todas_as_informacoes_do_header_batem
    fila4: onde_alguma_informacao_do_header_bate
server:
  port: 8082